### ISSUE TITLE
WindowServer high CPU %

### ISSUE THREAD

**Issue by ageorgios** [TheMickeyMike/hyperion-macOs#2]
While using the hyperion-project for Ambilight with a frequency of 10.0 (inteval 100ms) on a 4K display on a MacMini2018 I observe 60% CPU usage that makes the video playback and the general video performance juttery.

Does anyone else have the same problem?

**Comment by TheMickeyMike** [comment]
Hey, this repo contains only tool for installing official [Hyperion](https://github.com/hyperion-project/hyperion) with small patch. This seems to be problem with Hyperion itself, I'd recommend you to search help in official repo [Hyperion](https://github.com/hyperion-project/hyperion)
